module ScreenXTV
  LOGO = [
    " __              __ _____  _ _",
    "/ _| _ _  _  _  _\\ V /_ _|| | |",
    "\\_ \\///_|/o\\/o\\/ \\) ( | | | V |",
    "|__/\\\\L| \\( \\(L_n/_n_\\|_|  \\_/"
  ].join("\n")
end

__END__
log generated by
http://patorjk.com/software/taag/

 __              __ _____  _ _
/ _| _ _  _  _  _\ V /_ _|| | |
\_ \///_|/o\/o\/ \) ( | | | V |
|__/\\L| \( \(L_n/_n_\|_|  \_/
